### ISSUE TITLE
Add remaining icons to font

### ISSUE THREAD

**Issue by romansmirnov** [bpmn-io/cmmn-font#1]
- [x] Entry Criterion
- [x] Exit Criterion
- [x] Association
- [x] Case File Item
- [x] AutoComplete Marker
- [x] Manual Activation Marker
- [x] Required Marker
- [x] Repetition Marker
- [x] Event Listener
- [x] User Event Listener
- [x] Timer Event Listener
- [x] Tasks
- [x] Discretionary Tasks

**Comment by pedesen** [comment]
* [ ] Sentry
* [ ] Association
* [ ] Case File Item
